GET  http://localhost:5000/watches/667047a04aa64f22523d91bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJOYW1lIjoiYWRtaW4iLCJfaWQiOiI2Njc2NWU2NmMxYTM0MjQ0OTQ1YjcwM2QiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTkwMzQ0NDEsImV4cCI6MTcxOTEyMDg0MX0.DN8L31GRhxRJDkSjBeHdTEaUIvd6QeoxA37lxhSN-ws
Content-Type: application/json

{
  "watchName": "admin123",
  "image": "https://media.rolex.com/image/upload/q_auto/f_auto/c_limit,w_1920/v1/rolexcom/collection/watches-grid/popin-cards/m124300-0001/m124300-0001_v01",
  "price": 123123,
  "automatic": true,
  "watchDescription": "123456",
  "brand": "666d829c3d2f2cfe397f659a"
}
### Login

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "memberName": "admin",
  "password": "123456"
}

### LOGOUT
POST http://localhost:5000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJOYW1lIjoiYWRtaW4iLCJfaWQiOiI2Njc2NWU2NmMxYTM0MjQ0OTQ1YjcwM2QiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTkwMzQ0NDEsImV4cCI6MTcxOTEyMDg0MX0.DN8L31GRhxRJDkSjBeHdTEaUIvd6QeoxA37lxhSN-ws



### Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "memberName": "admin",
  "password": "123456",
  "name": "Boss",
  "YOB":1995
}

### Brand
DELETE  http://localhost:5000/brands/666d829c3d2f2cfe397f659a
Content-Type: application/json

{
  "brandName": "ABCDE123"
}

### 
GET  http://localhost:5000/watches

###
GET  http://localhost:5000/accounts/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJOYW1lIjoiYWRtaW4iLCJfaWQiOiI2Njc2NWU2NmMxYTM0MjQ0OTQ1YjcwM2QiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTkwMzM4NTAsImV4cCI6MTcxOTEyMDI1MH0.DG0OkYsO-fOBO7F99nck1QuQ26SZjXUUdWZQvAYvE0I


###  
POST http://localhost:5000/auth/change-password

