GET http://localhost:5000/watches/23esdfsd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJOYW1lIjoiYWRtaW4iLCJfaWQiOiI2Njc1OTAyYjg5Y2IzMWJlZDgzMDk5YzYiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzE4OTgxOTg1LCJleHAiOjE3MTkwNjgzODV9.rKFylxCZoou9wp9CR8A256a2tJDsizvUFkBZiyx-vW0

### Login

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "memberName": "admin",
  "password": "123456"
}


### Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "memberName": "admin",
  "password": "123456",
  "name": "Boss",
  "YOB":1995
}

### Brand
DELETE  http://localhost:5000/brands/66759950c95e608ae32c2e15
Content-Type: application/json

{
  "brandName": "ABCDE123"
}
